sudo: required

language: python
python:
  - "3.6"

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.8.0

before_install:
  - docker-compose up -d

script:
  - docker exec -it website python manage.py test
