version: '2'

services:
  db:
    image: postgres

  make_migration:
    build: .
    command: python manage.py makemigrations
    volumes:
      - .:/usr/src/app
    
    depends_on: 
      - db

  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - make_migration

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - make_migration
      - migration
