version: '2'

services:
  make_migration:
    build: .
    command: python manage.py makemigrations
    volumes:
      - .:/usr/src/app

  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/usr/src/app
    depends_on:
      - make_migration

  web:
    container_name: website
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - make_migration
      - migration
