# Generated by Django 2.0.7 on 2018-08-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='blogs',
        ),
    ]
