# Generated by Django 2.0.7 on 2018-08-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180814_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='no_of_images',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
