# Generated by Django 2.0.7 on 2018-08-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180815_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
