# Generated by Django 2.0.7 on 2018-08-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180818_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='views',
            new_name='author_views',
        ),
        migrations.AddField(
            model_name='website',
            name='tag_views',
            field=models.IntegerField(default=0),
        ),
    ]
