# Generated by Django 2.0.7 on 2018-08-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20180818_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rating',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
    ]
