# Generated by Django 2.0.7 on 2018-08-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
    ]
