# Generated by Django 2.0.7 on 2018-08-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='website',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
