# Generated by Django 2.0.7 on 2018-08-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180818_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='no_comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='no_posts',
            new_name='posts',
        ),
        migrations.AddField(
            model_name='author',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
